src/org/koi08r/ercscore/beans/ScoreBean.java
package org.koi08r.ercscore.beans;

import java.sql.Timestamp;
import java.text.SimpleDateFormat;


import org.koi08r.ercscore.parsers.CustomStringEscapeUtils;
import org.koi08r.ercscore.ws.Service;

public class ScoreBean {
	private int num = 0;
	private Timestamp ts = null;
	private String src = null;
	private String agent = null;
	private String ls = null;
	private String hw = null;
	private String cw = null;
	private String gz = null;
	private String el = null;
	private String sc = null;
	private String raw = null;
	private Integer lscheck = null; // TODO: Int ???

	private enum AgentsEnum {
		M,S,Z,A
	}

	public ScoreBean() {}

	public void setNum(int i) {
		num = i;
	}
	public int getNum() {
		return num;
	}

	public void setSrc(String s) {
		src = s;
	}
	public String getSrc() {
		return src;
	}

	public void setAgent(String s) {
		AgentsEnum e = AgentsEnum.valueOf(s);
		switch (e) {
		case M:
			agent = "Email";
			break;
		case S:
			agent = "SMS";
			break;
		case Z:
			agent = "SMS-ZP";
			break;
		case A:
			agent = "Asterisk";
			break;
		default:
			agent = s;
			break;
		}
	}
	public String getAgent() {
		return agent;
	}

	public void setLs(String s) {
		ls = s;
	}
	public String getLs() {
		return ls;
	}

	public void setHw(String s) {
		hw = s;
	}
	public String getHw() {
		return hw;
	}

	public void setCw(String s) {
		cw = s;
	}
	public String getCw() {
		return cw;
	}

	public void setGz(String s) {
		gz = s;
	}
	public String getGz() {
		return gz;
	}

	public void setEl(String s) {
		el = s;
	}
	public String getEl() {
		return el;
	}

	public void setSc(String s) {
		sc = s;
	}
	public String getSc() {
		return sc;
	}

	public void setRaw(String s) {
		raw = s;
	}
	public String getRaw() {
		return raw;
	}

	public void setTs(Timestamp d) {
		ts = d;
	}
	public Timestamp getTs() {
		return ts;
	}

	public void setLscheck(Integer i) {
		lscheck = i;
	}
	public Integer getLscheck() {
		return lscheck;
	}

	// Not beans functionality.
	public String getFormatDate() {
		SimpleDateFormat df = new SimpleDateFormat("dd.MM.yyy HH:mm:ss");
		return df.format(ts);
	}

	public String getFormatRaw() {
		return CustomStringEscapeUtils.escapeHtml4(raw);
	}

	public String getFormatLsCheck() {
		return Service.StrError(lscheck);
	}

}

src/org/koi08r/ercscore/srvl/Controller.java
package org.koi08r.ercscore.srvl;

import java.io.IOException;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/ctrl")
public class Controller extends HttpServlet {
	private static final long serialVersionUID = 1L;

    public Controller() {
    }

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		this.getServletConfig().getServletContext().setAttribute("TestAttr", "Hello");

		String page = request.getParameter("page");
		String forward_page = "index.jsp";

		if (page != null && page.equals("scores")) {
			forward_page = "/WEB-INF/jsp/dbq.jsp";
		}

		RequestDispatcher dispatcher = request.getRequestDispatcher(forward_page);
		dispatcher.forward(request, response);
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doGet(request, response);
	}

}

WebContent/WEB-INF/jsp/dbq.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Query counters database</title>
<style type="text/css">
		@font-face {
			font-family: UbuntuMono;
			src: url(ttf/ubuntumono.ttf);
		}

		body {
			font-family: UbuntuMono;
		}
		.b_search {
			background: transparent url(img/search-20x20.png) no-repeat center top;
			/* border: none; */
			border-radius:5px;
			border-width:1px;
			border-style:solid;
			border-color:#919191;
			cursor:pointer;
		}
		.b_search:hover {
			background: transparent url(img/_search-20x20.png) no-repeat center top;
		}

		.inp_search {
			border: none;
			padding: 0px;
			background-color: #D1D2CF;
		}

		a:link {
			color: black;
		}
		a:visited {
			color: black;
		}
		a:active {
			color: black;
		}
		a:hover {
			color: black;
		}

        .t_data {
                background-color: #D1D2CF;
        }

		.t_inp {
			border: none;
			padding: 0px;
		}


        .t_header {
        		color: white;
                background-color: #000000;
                -webkit-border-radius: 8px 8px 0 0;
				-moz-border-radius: 8px 8px 0 0;
				border-radius: 8px 8px 0 0;
        }
        .txt_error {
        	color: red;
        }
        .txt_success {
        	color: green;
        }
        td {
        		padding: 5px;
        		vertical-align: top;
        		border-width: 1px;
				border-color: #000000;
                border-style: solid;
        }
        table {
				/* width: 90%; */
        		vertical-align: top;
                border-style: none;
        }
		.raw_content {
			max-height: 300px;
			border: none;
			overflow-y: scroll;
			overflow-x: scroll;
		}
</style>
</head>
<body>
<center>

<c:set var="results_per_page" value="${10}" scope="request" />

<p>
	<a href="/ercscore/dbq">home</a>
	<a href=#bottom>bottom</a>
</p>

<form action="/ercscore/dbq?limit=${results_per_page}" method="get">
<table border="2px">
<tr>
	<td class="t_header">
		Поиск по Лс
	</td>
</tr>
<tr>
	<td class="t_inp">
		<input class="inp_search" type="text" name="ls" value="">
		<input class="b_search" type="submit" value="">
	</td>
</tr>
</table>
</form>

<form action="/ercscore/dbq?limit=${results_per_page}" method="get">
<table border="2px">
<tr>
	<td class="t_header">
		Поиск по источнику
	</td>
</tr>
<tr>
	<td class="t_inp">
		<input class="inp_search" type="text" name="source" value="">
		<input class="b_search" type="submit" value="">
	</td>
</tr>
</table>
</form>

<form action="/ercscore/dbq?limit=${results_per_page}" method="get">
<table border="2px">
<tr>
	<td class="t_header">
		Выбрать всё
	</td>
</tr>
<tr>
	<td class="t_inp">
		<input class="inp_search" type="text" name="all" value="" readonly>
		<input class="b_search" type="submit" value="">
	</td>
</tr>
</table>
</form>

<p>_</p>

<c:if test="${not empty query}">
	Запрос: ${query}
</c:if>
<br>

<c:choose>
	<c:when test="${empty scores}">
		Нет результатов.<br>
	</c:when>
	<c:otherwise>
		<c:set var="itr" value="${0}" scope="request" />
			<c:if test="${rowleft > 0}">
				Результатов в БД (осталось/всего): ${rowleft}/${rownumber}.
				 <a href="/ercscore/dbq?${action}&limit=${results_per_page}&offset=${rownumber-rowleft}">ещё</a><br>
			</c:if>
			Всего результатов на странице: ${fn:length(scores)}<br>
			<p>_</p>
			<table border="2px">
			<c:forEach var="score" items="${scores}">
		  	<tr>
  				<c:set var="itr" value="${itr + 1}" scope="request" />
  				<td class="t_header" colspan="10"> * № ${itr}</td>
  			</tr>
  			<tr>
    			<td class="t_header">Дата обработки</td>
			    <td class="t_header">Источник</td>
			    <td class="t_header">Агент</td>
			    <td class="t_header">Результат</td>
			    <td class="t_header">Лс</td>
			    <td class="t_header">Гв</td>
			    <td class="t_header">Хв</td>
			    <td class="t_header">Гз</td>
			    <td class="t_header">Эл</td>
			    <td class="t_header">Сч</td>
  			</tr>
  			<tr>
			    <td class="t_data">${score.formatDate}</td>
			    <td class="t_data">${score.src}</td>
			    <td class="t_data">${score.agent}</td>
			    <c:choose>
   			    <c:when test="${score.lscheck == 1}">
		    		<td class="t_data txt_success">${score.formatLsCheck}</td>
				</c:when>
				<c:otherwise>
					<td class="t_data txt_error">${score.formatLsCheck}</td>
				</c:otherwise>
				</c:choose>
			    <td class="t_data">${score.ls}</td>
			    <td class="t_data">${score.hw}</td>
			    <td class="t_data">${score.cw}</td>
			    <td class="t_data">${score.gz}</td>
			    <td class="t_data">${score.el}</td>
			    <td class="t_data">${score.sc}</td>
			    <%-- <td class="t_data"><div class="raw_content">${score.formatRaw}</div></td> --%>
  			</tr>
  			<tr>
  				<td class="t_header" colspan="10">Необработанное сообщение</td>
  			</tr>
  			<tr>
  				<td class="t_data" colspan="10"><div class="raw_content">${score.formatRaw}</div></td>
  			</tr>
  			</c:forEach>
  			</table>
	</c:otherwise>
</c:choose>




<%-- score.formatRaw --> escapeXml( java.lang.String) --%>

<p><a name="bottom" href=#>top</a></p>

</center>
</body>
</html>

WebContent/axis2-web/ActivateService.jsp
<%--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements. See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership. The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License. You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied. See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  --%>

<%@ page import="org.apache.axis2.Constants,
                 org.apache.axis2.description.AxisService,
                 java.util.Collection,
                 java.util.HashMap,
                 java.util.Iterator"%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<jsp:include page="include/adminheader.jsp"></jsp:include>
<h1>Turn On Service</h1>
<form method="get" name="serviceActivate" action="axis2-admin/activateService">
  <table width="100%"  border="0">
<tr>
  <td colspan="2" >
     <p>The services that are inactive are listed below. Although you can activate the services from this page, once system is restarted the services will be inactive again</p>
  </td>
  </tr>
  <tr>
  <%
HashMap services = (HashMap)request.getSession().getAttribute(Constants.SERVICE_MAP);
Collection col = services.values();
String html = "";
int count = 0;

for (Iterator iterator = col.iterator(); iterator.hasNext();) {
	AxisService axisServices = (AxisService) iterator.next();
	if(!axisServices.isActive()){
		count++;
		html += "<option value='" + axisServices.getName() + "'>";
		html += axisServices.getName() + "</option>";
	}
}
request.getSession().setAttribute(Constants.SERVICE_MAP,null);
if (count > 0) {
%>
  
    <td width="20%"> Select Service : </td>
    <td width="80%">
       <select name="axisService" class="selectBoxes">
		<%=html%>
		</select>
  </tr>
  <tr>
    <td width="20%">Activate Service </td>
    <td width="80%"><input type="checkbox" name="turnon">
    </td>
  </tr>
  <tr>
  <td>&nbsp;</td>
  <td>
    <input name="submit" type="submit" value=" Activate " >
   <input name="reset" type="reset" value=" Clear " >
  </td>
<%
} else {
	%>
	<td colspan="2">No inactive services present.</td>
	<%
}
%>
  </tr>

</table>
</form>
<jsp:include page="include/adminfooter.inc"></jsp:include>

WebContent/axis2-web/EngageToServiceGroup.jsp
<%--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements. See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership. The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License. You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied. See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  --%>

<%@ page contentType="text/html; charset=iso-8859-1" language="java" import="org.apache.axis2.Constants,
                                                                             org.apache.axis2.description.AxisModule,
                                                                             org.apache.axis2.description.AxisServiceGroup,
                                                                             java.util.Collection" %>
<%@ page import="java.util.HashMap"%>
<%@ page import="java.util.Iterator"%>
<%@ page import="org.apache.axis2.util.Utils" %>
<jsp:include page="include/adminheader.jsp"></jsp:include>
<%
    String status = (String)request.getSession().getAttribute(Constants.ENGAGE_STATUS);
    HashMap moduels = (HashMap)request.getSession().getAttribute(Constants.MODULE_MAP);
    request.getSession().setAttribute(Constants.MODULE_MAP,null);
    Collection moduleCol =  moduels.values();
    Iterator servicesGroups = (Iterator)request.getSession().getAttribute(Constants.SERVICE_GROUP_MAP);
    request.getSession().setAttribute(Constants.SERVICE_GROUP_MAP,null);
%>
<h1>Engage Module for a Service Group</h1>
<p>To engage a module for a set of services grouped as an axis service group,</p>

    <ol>
        <li>select the module you want to engage </li>
        <li>select the axis service group you like the module to be engaged.</li>
        <li>click "Engage".</li>
    </ol>


<%
	if (!moduleCol.iterator().hasNext()) {%>
		<p>No modules are present to be engaged.</p>
	<%} else {
		if  (!servicesGroups.hasNext()) {%>
		<p>No Axis service groups are present to be engaged.</p>
		<%} else {
%>
<form method="get" name="selectModuleForm" action="axis2-admin/engageToServiceGroup">
    <table border="0" width="100%" cellspacing="1" cellpadding="1">
        <tr>
            <td>Select a Module :</td>
        </tr>
        <tr>
            <td>
                <select name="modules">
                    <%
                for (Iterator iterator = moduleCol.iterator(); iterator.hasNext();) {
                    AxisModule axisOperation = (AxisModule) iterator.next();
                    String modulename = axisOperation.getName();
            %> <option  align="left" value="<%=modulename%>"><%=modulename%></option>
                    <%
                }
             %>
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;
                &nbsp;
            </td>
        </tr>
        <tr>
            <td>Select a Service Group :</td>
        </tr>
        <tr>
            <td>
                <select name="axisService">
                    <%

                        while(servicesGroups.hasNext()){
                            AxisServiceGroup axisServiceGroup = (AxisServiceGroup) servicesGroups.next();
                            String serviceName = axisServiceGroup.getServiceGroupName();
                    %> <option  align="left" value="<%=serviceName%>"><%=serviceName%></option>
                    <%
                        }

                    %>
                </select>
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;
                &nbsp;
            </td>
        </tr>
        <tr>
            <td>
                <input name="submit" type="submit" value=" Engage " >
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;
                &nbsp;
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;
                &nbsp;
            </td>
        </tr>
        <tr>
            <td>
                <textarea cols="50"  <%
                    if(status == null){
                %>
                          style="display:none"
                        <%
                            } %>
                        ><%=Utils.sanitizeWebOutput(status)%></textarea>
            </td>
        </tr>
    </table>
</form>
<%
		}
	}
%>
<jsp:include page="include/adminfooter.inc"></jsp:include>

WebContent/axis2-web/Login.jsp
<%--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements. See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership. The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License. You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied. See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  --%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
  <head>
    <jsp:include page="include/httpbase.jsp"/>
    <title>Login to Axis2 :: Administration page</title>
    <link href="axis2-web/css/axis-style.css" rel="stylesheet" type="text/css">
  </head>

  <body onload="javascript:document.LoginForm.userName.focus();">
    <jsp:include page="include/header.inc"/>
    <jsp:include page="include/link-footer.jsp"/>
    <table class="FULL_BLANK">
      <tr>
        <td valign="top">
        	<h2>Welcome :</h2>
        	<p>Welcome to the Axis2 administration console. From inside the Axis2 administration console you can :</p>
	    	<ul style="list-style: none;" class="loginUL">
	       		<li>Check on the health of your Axis2 deployment.</li>
 	       		<li>Change any parameters at run time.</li>
 	       		<li>Upload new services into Axis2 [Service hot-deployment].</li>
 	   		</ul>
	        <font color="orange">Warning: Please note that configuration changes done through the administration console
    	    will be lost when the server is restarted.</font>
    	</td>
        <td valign="top" align="left">
          <form method="post" name="LoginForm" action="axis2-admin/login">
            <table class="LOG_IN_FORM">
              <tr>
                <td align="center" colspan="2" bgcolor="#b0b0b0" color="#FFFFFF"><font color="#FFFFFF">Login</font></td>
              </tr>
              <tr>
                 <td align="center" colspan="2">&nbsp;</td>
               </tr>
              <tr>
                <td align="right">Username:</td>
                <td><input align="left" type="text" name="userName" tabindex="1">
                </td>
              </tr>
              <tr>
                <td align="right">Password : </td>
                <td><input align="left" type="password" name="password" tabindex="2">
                </td>
              </tr>
              <tr>
                <td colspan="2">
                  <br>
                </td>
              </tr>
              <tr>
                <td align="center" colspan="2">
                  <input name="cancel" type="reset" value=" Clear "> &nbsp; &nbsp;
                  <input name="submit" type="submit" value=" Login ">
                </td>
              </tr>
              <tr>
                <td align="center" colspan="2">
                  <font color="red">&nbsp;<% if (request.getAttribute("errorMessage") != null) {%><%= request.getAttribute("errorMessage")%><% } %>&nbsp;</font>
                </td>
              </tr>
            </table>
          </form>
          <br/><br/><br/><br/><br/><br/>
        </td>
      </tr>
    </table>
    <p>Test</p>
    <jsp:include page="include/footer.inc"/>
  </body>
</html>

WebContent/axis2-web/admin.jsp
<%--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements. See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership. The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License. You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied. See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  --%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<jsp:include page="include/adminheader.jsp"></jsp:include>
<h1>Welcome to Axis2 Web Admin Module !!</h1>
<p>You are now logged into the Axis2 administration console from inside
the console you will be able to</p>
    <ul>
        <li>to check on the health of your Axis2 deployment.</li>
        <li>to change any parameters at run time.</li>
        <li>to upload new services into Axis2 [Service hot-deployment].</li>
    </ul>

<jsp:include page="include/adminfooter.inc"></jsp:include>

WebContent/axis2-web/deleteService.jsp
<%--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements. See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership. The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License. You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied. See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  --%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<jsp:include page="include/adminheader.jsp"/>
<p><%=request.getSession().getAttribute("status")%></p>
<p>Click <a href="services/listServices">here</a> to go to the service list page</p>
<jsp:include page="include/adminfooter.inc" />

WebContent/axis2-web/engagingtoaservice.jsp
<%--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements. See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership. The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License. You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied. See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  --%>

<%@ page contentType="text/html; charset=iso-8859-1" language="java" import="org.apache.axis2.Constants,
                                                                             org.apache.axis2.description.AxisModule,
                                                                             org.apache.axis2.description.AxisService,
                                                                             java.util.Collection,
                                                                             java.util.HashMap,
                                                                             java.util.Iterator"
         %>
<%@ page import="org.apache.axis2.util.Utils" %>
<jsp:include page="include/adminheader.jsp"></jsp:include>
<%
    String status = (String) request.getSession().getAttribute(Constants.ENGAGE_STATUS);
%>
<h1>Engage Module for a Service</h1>

<p>To engage a module for a axis service,</p>

    <ol>
        <li>select the module you want to engage</li>
        <li>select the axis service you like the module to be engaged.</li>
        <li>click "Engage".</li>
    </ol>

<form method="get" name="selectModuleForm" action="axis2-admin/engageToService">
    <table border="0" width="100%" cellspacing="1" cellpadding="1">
        <tr>
            <td>
                &nbsp;
                &nbsp;
            </td>
        </tr>
        <tr>
            <td>Select a Module :</td>
        </tr>
        <tr>
            <td>
                <select name="modules">
                    <%

                        HashMap moduels = (HashMap)request.getSession().getAttribute(Constants.MODULE_MAP);
                        request.getSession().setAttribute(Constants.MODULE_MAP,null);
                        Collection moduleCol =  moduels.values();
                        for (Iterator iterator = moduleCol.iterator(); iterator.hasNext();) {
                            AxisModule axisOperation = (AxisModule) iterator.next();
                            String modulename = axisOperation.getName();

                    %>
                    <option align="left" value="<%=modulename%>"><%=modulename%>
                    </option>
                    <%

                       }

                    %>
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;
                &nbsp;
            </td>
        </tr>
        <tr>
            <td>Select a Service :</td>
        </tr>
        <tr>
            <td>
                <select name="axisService">
                    <%

                        HashMap services = (HashMap)request.getSession().getAttribute(Constants.SERVICE_MAP);
                        Collection serviceCol =  services.values();
                        for (Iterator iterator = serviceCol.iterator(); iterator.hasNext();) {
                            AxisService axisService = (AxisService)iterator.next();
                            String serviceName = axisService.getName();

                    %>
                    <option align="left" value="<%=serviceName%>"><%=serviceName%>
                    </option>
                    <%

                       }
                       request.getSession().setAttribute(Constants.SERVICE_MAP,null);

                    %>
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;
                &nbsp;
            </td>
        </tr>
        <tr>
            <td>
                <input name="submit" type="submit" value=" Engage ">
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;
                &nbsp;
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;
                &nbsp;
            </td>
        </tr>
        <tr>
            <td>
                <textarea cols="50"  <%
                    if (status == null) {
                %>
                          style="display:none"
                        <%
                            } %>
                        ><%=Utils.sanitizeWebOutput(status)%>
                </textarea>
            </td>
        </tr>
    </table>
</form>
<jsp:include page="include/adminfooter.inc"></jsp:include>


WebContent/error.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Error</title>
</head>
<body>

Error

</body>
</html>

WebContent/index.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Index</title>
</head>
<body>
<a href="/ercscore/ctrl?page=scores">Счетчики</a>
</body>
</html>